# Generated by Django 6.0.4 on 2026-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SVG', 'Svg')], db_index=True, max_length=4)),
                ('size', models.JSONField()),
                ('color', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(verbose_name='date generated')),
            ],
        ),
    ]
